// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw1IVMgqcfH1TDLSnnUphdxv5Wdxz0iz0',
    appId: '1:154620576089:web:cb0cffb93c7b4b1792cc48',
    messagingSenderId: '154620576089',
    projectId: 'shopify-firebase-8c87c',
    authDomain: 'shopify-firebase-8c87c.firebaseapp.com',
    storageBucket: 'shopify-firebase-8c87c.firebasestorage.app',
    measurementId: 'G-D3TEH3K79T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcndZtLeRStol_H-9njPvbSrgQGT_o8vI',
    appId: '1:154620576089:android:1ff7f64e21af59b792cc48',
    messagingSenderId: '154620576089',
    projectId: 'shopify-firebase-8c87c',
    storageBucket: 'shopify-firebase-8c87c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRXnc8kdQQkTxCO9WR0TmATYEVLUk5mh8',
    appId: '1:154620576089:ios:3ba572c68309278892cc48',
    messagingSenderId: '154620576089',
    projectId: 'shopify-firebase-8c87c',
    storageBucket: 'shopify-firebase-8c87c.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );
}
